name: Arduino

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  uno-r4-minima:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Compile PicoMesh examples
        uses: arduino/compile-sketches@v1
        with:
          fqbn: arduino:renesas_uno:minima
          sketch-paths: |
            - examples/ArduinoHeartbeatNode
            - examples/ArduinoHeartbeatController
            - examples/ArduinoMultiNodeController
            - examples/ArduinoReliableCommandController
          enable-warnings-report: true
